# Generated by Django 4.2.3 on 2023-10-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_data',
            new_name='publish',
        ),
    ]
