# Generated by Django 4.2.3 on 2023-10-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0002_rename_publish_data_post_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
