# Generated by Django 4.2.3 on 2023-10-26 09:08

import Gsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_second',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=Gsite.models.user_directory_path),
        ),
    ]
