# Generated by Django 4.2.3 on 2023-10-26 09:58

import Gsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0008_post_content_second_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_content',
            field=models.ImageField(null=True, upload_to=Gsite.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image_content_second',
            field=models.ImageField(null=True, upload_to=Gsite.models.user_directory_path),
        ),
    ]
