# Generated by Django 4.2.3 on 2023-10-26 10:15

import Gsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0009_post_image_content_post_image_content_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to=Gsite.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_content_second',
            field=models.ImageField(blank=True, null=True, upload_to=Gsite.models.user_directory_path),
        ),
    ]
