# Generated by Django 4.2.3 on 2023-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0010_alter_post_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_final',
            field=models.TextField(null=True),
        ),
    ]
